--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ree-jp-minecraft/MysqlLogger
build-by-default: true
branches:
  - path
projects:
  MysqlLogger:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0
...
