--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ree-jp-minecraft/MysqlLogger
build-by-default: true
branches:
- master
projects:
  MysqlLogger:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0
...
